module.exports = {
    genericsElements: {
        loading: ".loading",
        btn: ".btn.btn-primary",
        table: "table",
        buttonVer: ".btn.btn-xs.btn-default",
        toast: ".Toastify__toast-body",
        viewLink: 'a[href$="view"]',
        editLink: 'a[href$="edit"]',
        newLink: 'a[href$="new"]',
        genericResultLink: ".table a[href]",
        returnButton: '.back-button',
        tooltip: '.tooltip-icon',
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        modalRollbackButton: ".modal-footer .btn.btn-default",
        locationFilterHeader: "#content .location-selector .btn-link span",
        paginationFooter: ".pagination",
        paginationNext: ".pagination [data-page*='next']",
        paginationPrevious: ".pagination [data-page*='previous']",
        paginationNumber2: ".pagination [data-page*='2']",
        paginationNumber3: ".pagination [data-page*='3']",
        locationFilterCleanerButton: ".location-selector .clearfix .clear",
        locationFilterApplyButton: ".location-selector .clearfix .apply",
        locationFilterSelectAllOption: ".location-selector .select-all span",
        calendarFilter: ".date-range .btn span",
        opcaoFiltroDataSelecionado: ".date-range .active",
        mainCheckBox: "thead [type*='checkbox']",
        emptyTable: ".empty-table",
        locationSearchField: ".search-field .form-group input",
        linksMenu: ".btn-group.sidebar-brand",
        headerTitle: '#app-title h1',

        //Visao Geral /dashboard
        tableDeadline: ".deadline-table.table.table-hover.table-striped.table-sortable.table-wrap",
        tablePedidosParalisados: ".paralyzed-table.table.table-hover.table-striped.table-sortable.table-wrap",
        tablePedidoStatusEntrega: ".table.table-hover.table-striped.table-sortable.table-wrap",
        tableFiliais: ".table.table-hover.table-striped.table-sortable.table-wrap",
        tableFiliaisStatusEntrega: ".table.table-hover.table-striped.table-sortable.table-wrap",
        dashboardCicloVidaRetiradaLoja: ".row.dashboard-graph.pickup-lifecycle",
        dashboardCicloVidaEnvioLoja: ".row.dashboard-graph.shipment-lifecycle",

        //Entregas-Todas as entregas /deliveries/all
        tableListaEntregas: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Entregas-Falhas /deliveries/failures?situation=notProcessed
        tableListaEntregasComFalha: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Entregas-Finalizadas /deliveries/delivered
        tableListaEntregasFinalizas: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Filiais-Cadastro Filiais /locations
        tableCadastroFiliais: ".table.table-hover.table-striped.table-sortable.table-wrap",

        //Filiais-Priorização Filiais /locations/priority
        tableConfiguracaoPriorizacao: ".table.table-hover.table-striped.table-sortable.table-wrap",

        //Estoque-Desabilitados stock/disabled
        tableEstoqueDesabilitados: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Macrorregioes /macroregions
        tableMacrorregioes: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Envio pela Loja-Modalidades Frete /shipment/freight-methods
        tableModalidadesDeFrete: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Envio pela Loja-Transportadoras /shipment/carriers
        tableTransportadoras: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Envio pela Loja-Tabelas Frete /shipment/freight-tables
        tableTabelasFrete: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Dias Recesso /holidays
        tableDiasDeRecesso: ".table.table-hover.table-striped.table-sortable.table-wrap",

        //Pools /pools
        tablePools: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //GrupoEmpresarial /companies
        tableGrupoEmpresarial: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Marcas /brands
        tableMarcas: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Regionais /location-groups
        tableRegionais: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Usuarios-Usuarios OMS /users/cockpit
        tableUsuariosOMS: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Usuarios-Operadores Loja /users/in-store
        tableOperadoresLoja: ".table.table-hover.table-striped.table-rounded.table-sortable.table-wrap",

        //Usuarios-Permissoes /users/permissions
        tablePermissoes: ".table.table-hover. table-striped.table-rounded.table-sortable.table-wrap",
    },
    dashboard: {
        loading: ".loading",
        tableDeadline: ".deadline-list table td",
        tablePedidosParalisados: ".paralyzed-list table td",
        tablePedidoStatusEntrega: ".fulfillments-by-status table td",
        tableFiliais: ".status-grouped-by-location table td",
        tableFiliaisStatusEntrega: ".location-by-status-list table",
        dashboardCicloVidaRetiradaLoja: ".row.dashboard-graph.pickup-lifecycle",
        dashboardCicloVidaEnvioLoja: ".row.dashboard-graph.shipment-lifecycle",
    },

    accounts: {
        userEmail: ".input-group #user_email",
        userPass: ".input-group #user_password",
        loginButton: ".btn.btn-primary",
        clientCombo: ".btn-group.custom-dropdown.store-selector",
        clientTypeField: ".search-field .form-control",
        headerMenu: "#header-menu"
    },
    brands: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='brandId']",
        tradingName: "[name='tradingName']",
        name: "[name='name']",
        company: ".rw-input.rw-dropdown-list-input",
        loading: ".loading",
        list: ".brands table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        toast: ".Toastify__toast-body"
    },
    companies: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='companyId']",
        name: "[name='name']",
        loading: ".loading",
        list: ".companies table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary"
    },
    customer_services: {
        showHideDetailsButton: ".show-details span",
        orderNumberOrderDetail: ".order-details .col-sm-2 .sm-section-title",
        deliveriesOrderDetail: ".order-details .col-sm-7 .sm-section-title",
        costumerDataOrderDetail: "//div[@class='order-details']/div/div[@class='row has-divider']/div[1]/h3",
        orderDataOrderDetail: "//div[@class='order-details']/div/div[@class='row has-divider']/div[2]/h3",
        billingAddressOrderDetail: "//div[@class='order-details']/div/div[@class='row has-divider']/div[3]//h3",
        statusTag: "h2 span.status-tag", //Generic
        actionsButtons: ".col-xs-3 button", //Generic
        locationPickupData: ".fulfillment-pickup div",
        lifeCycleLabel: ".fulfillment-lifecycle h3",
        lifeCycleGraphic: ".lifecycle-graph",
        labelDeadLine: ".fulfillment-deadline",
        modalConfirmButton: ".confirm-modal .btn.btn-primary",
        modalRollbackButton: ".confirm-modal .btn.btn-default",
        searchOrderIdField: "#orderId",
        searchNameField: "#customerName",
        searchCpfField: "#customerIDNumber",
        searchEmailField: "#customerEmail",
        refundType: ".rw-widget-input",
        //exchange-return
        checkAllProducts: "thead [type*=checkbox]",
        returnNumberProducts: ".fulfillment-products tbody tr td:first-child .text-box span",
        checkTableLine: "tbody [type*='checkbox']",
        actionsButton: ".btn.btn-primary.dropdown-toggle",
    },
    deliveries_all: {
        textFieldBuscarEntrega: ".form-group.has-feedback.search-wrapper.fulfillment-search [placeholder='Buscar']",
        tableEmpty: ".empty-table p",
        loading: ".loading",
        buttonBuscar: ".fa.fa-search.form-control-feedback",
        list: ".deliveries table",
        locationNameColumnTable: "tbody tr td:nth-child(6)",
        orderSearchField: ".fulfillment-search input",
        iconSearchButton: ".fulfillment-search button",
        idOrderField: ".order-id",
        modalConfirmButton: ".confirm-modal .btn.btn-primary",
        modalRollbackButton: ".confirm-modal .btn.btn-default",
        refundType: ".rw-widget-input",
        statusTag: "h2 span.status-tag",
        salePointButton: "#rw_3_input[role='combobox'] .rw-dropdown-list-input"
    },
    deliveries_delivered: {
        loading: ".loading",
        list: ".deliveries table",
        textFieldBuscarEntrega: ".form-group.has-feedback.search-wrapper.fulfillment-search [placeholder='Buscar']",
        tableEmpty: ".empty-table p",
        buttonBuscar: ".fa.fa-search.form-control-feedback",
        orderId: ".order-id",
        orderIdColumn: ".table.table-hover tbody tr td:nth-child(2)"
    },
    deliveries_failures: {
        loading: ".loading",
        list: ".deliveries table",
        dropDownLocation: '.location-selector .multiselect-toggle',
    },
    deliveries_presales: {
        loading: ".loading",
        list: ".deliveries table",
        orderSearchField: ".fulfillment-search input",
        iconSearchButton: ".fulfillment-search button",
        idOrderField: ".order-id",
        modalConfirmButton: ".confirm-modal .btn.btn-primary",
        modalRollbackButton: ".confirm-modal .btn.btn-default",
        refundType: ".rw-widget-input",
        statusTag: "h2 span.status-tag",
        locationNameColumnTable: "tbody tr td:nth-child(5)"
    },
    financial_calculation_basis: {
    },
    financial_period_closing: {
        button: ".btn.btn-xs.btn-default",
        table: ".table.table-hover.table-striped",
        dateCutInputField: "input.form-control",
        labelInformDateDate: ".col-md-12", //Generic
        disabledApurarButton: ".btn.btn-xs.btn-default[disabled]",    
        qtdReprocessamentos: "tbody tr",
        tableBody: "table tbody",
        emptyTable: ".empty-table"
    },
    financial_reports_accounting: {
    },
    financial_reports_financial: {
        seletorPeriodo: ".closure-selector .dropdownlist-toggle",
        abaConsolidado: "#react-tabs-16",
        consolidadoToggleSeletorFilial: "#react-tabs-17 .dropdownlist-toggle",
        consolidadoExportarTabela: "#react-tabs-17 .fa-cloud-download",
        abaDetalhado: "#react-tabs-18",
        detalhadoSeletorFilialOrigem: "#react-tabs-19 .origin-selector",
        detalhadoSeletorFilialDestino: "#react-tabs-19 .destination-selector",
        detalhadoAdicionarAjuste: "#react-tabs-19 .btn-primary .fa-plus",
        detalhadoExportarTabela: "#react-tabs-19 .fa-cloud-download",
        abaPorFilial: "#react-tabs-20",
        porFilialSeletor: "#react-tabs-21 .location-selector",
        periodSelectorData: ".closure-selector .dropdownlist-list span",
        tableReportsFinancial: "table tbody tr",
        tabDetalhado: ".react-tabs__tab-list li:nth-child(2)",
        colunaValorFrete: "table tbody tr td:nth-child(15)",
        addManualAdjustmentButton: ".clearfix .fa-plus",
        adjustmentFormRadioManual: ".adjustment-form .radio [value='manual']",
        adjustmentFormRadioOrder: ".adjustment-form .radio [value='fulfillment']",
        adjustmentFormOrderIdField: ".adjustment-form #orderId",
        adjustmentFormCombo: ".adjustment-form [role='combobox'] button",
        adjustmentFormValueField: ".adjustment-form #value",
        adjustmentFormRadioCredit: ".adjustment-form .radio [value='credit']",
        adjustmentFormRadioDebit: ".adjustment-form .radio [value='debit']",
        adjustmentFormDescField: ".adjustment-form #description",
        adjustmentFormSaveButton: ".adjustment-form .btn-primary",
        adjustmentFormCancelButton: ".adjustment-form .btn-default",
        mainTableSelectedReport: ".react-tabs__tab-panel--selected .table-container.scrollable tbody tr", //Lines
        subTableSelectedReport: ".react-tabs__tab-panel--selected .table-container.fixed tbody td", //Cells
        locationFilterConsolidatedReport: ".react-tabs__tab-panel--selected .origin-selector .btn-link",
        locationSearchFilterConsolidatedReport: ".origin-selector input",
        detailedDropDownButton: ".react-tabs__tab-panel--selected [role='presentational']",
        adjustmentFormDropDownButtons: ".adjustment-form [role='combobox']"
    },
    financial_settings: {
        checkboxValorTotalPedido: ".radio [type='radio'][value='order']",
        checkboxValorTotalMercadoria: ".radio [type='radio'][value='merchandise']",
        checkboxTotal: ".radio [type='radio'][value='full']",
        checkboxParcial: ".radio [type='radio'][value='partial']",
        checkboxNaoRealizavel: ".radio [type='radio'][value='notRealizable']",
        inputDataInicio: "[placeholder='Data de início']",
        inputDataFim: "[placeholder='Data de fim']",
        buttonAdicionarVigencia: ".fa.fa-plus",
        button: ".fa.fa-check",
        buttonRemoverVigencia: ".btn.btn-remove",
        listDataVigenciaCadastrada: "ul.bases",
        buttonNaolModal: "button[data-bb-handler='cancel']",
        buttonSimModal: "button[data-bb-handler='confirm']",
        buttonOkModal: "button[data-bb-handler='ok']",
        modal: ".modal-backdrop.fade",
        primeiraColunaUltimoRegistro: "tbody tr td:nth-child(1)",
        segundaColunaUltimoRegistro: "tbody tr td:nth-child(2)",
        textVigenciaAtual: ".bases li .value",
        columnTypeTable: "tbody td:first-child",
    },
    holidays: {
        btn: ".complementary-header .btn.btn-primary",
        name: "#name",
        dataAbrangencia: ".rw-widget-input.rw-input",
        loading: ".loading",
        labelDetalhesPedido: '#app-title h1',
        fieldName: "[name='name']",
        startZIP: "#start",
        endZIP: "#end",
        addZipButton: ".form-group.boxed .btn.btn-primary",
        changeStatus: "[for='toggleactive']",
        chkSaturday: "[name='closedOnSaturdays']",
        chkSunday: "[name='closedOnSundays']",
        disabledSalveButton: ".complementary-header .btn-primary[disabled]",
        disabledAddZipButton: ".form-group.boxed .btn.btn-primary[disabled]",
    },
    index: {
    },
    location_groups: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='locationGroupId']",
        name: "[name='name']",
        zipCode: "[name='address.zip']",
        address1: "[name='address.address1']",
        number: "[name='address.number']",
        address2: "[name='address.address2']",
        neighbourhood: "[name='address.neighbourhood']",
        city: "[name='address.city']",
        state: "[name='address.state']",
        country: "[name='address.country']",
        loading: ".loading",
        list: ".location-groups table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary"
    },
    locations_closure: {
        button: ".btn.btn-primary",
        tableEncerramentosAgendados: ".location-closures.has-header-actions .row:nth-child(2) table",
        emptyTableEncerramentosAgendados: ".location-closures.has-header-actions .row:nth-child(4) table",
        tableEncerramentosRealizados: ".location-closures.has-header-actions .row:nth-child(2) .empty-table",
        emptyTableEncerramentosRealizado: ".location-closures.has-header-actions .row:nth-child(4) .empty-table",
        linkRelatorioFinanceiro: "a[href*='reports/financial']",
        linkRelatorioContabil: "a[href*='reports/accounting']",
        linkListarEncerramentos: ".back-button",
        comboboxFilial: "#rw_1_input",
        radioEncerrarAoFimDoDiaDeHoj: ".radio [value='today']",
        agendarEncerramento: ".radio [value='scheduled']",
    },
    locations_priority: {
        seletorFilial: "#content .location-selector",
        abaEnvioLoja: "#react-tabs-0",
        itensPorPaginaEnvioLoja: "#react-tabs-1 .rw-input",
        gestaoIndicadores: ".btn-secondary", // + text
        abaEnvioLojaIndicador: "#react-tabs-4",
        salvarEnvioLojaIndicador: "#react-tabs-5 .btn-primary",
        criarIndicador: "#content .btn-secondary",
        campoId: "#indicatorId",
        campoNome: "#name",
        checkEnviaLoja: "[name*='SHIPMENT']",
        checkRetiraLoja: "[name*='PICKUP']",
        campoDescricao: "#description",
        salvarIndicador: ".btn-primary",
        abaRetiraLoja: "#react-tabs-2",
        locationSelector:".location-selector .multiselect-toggle",
        tableLocationScoreShipment: ".scores-container.shipment .location-scores .locations-scores tbody",
        firstTdTableLocationScoreShipment: ".scores-container.shipment .location-scores .locations-scores tbody  tr td:nth-child(1)",
        tabEnvioPelaLoja: ".react-tabs__tab-list li:nth-child(1)",
        tabRetiraEmLoja: ".react-tabs__tab-list li:nth-child(2)",
        tableLocationScorePickup: ".scores-container.pickup .location-scores .locations-scores tbody",
        firstTdTableLocationScorePickup: ".scores-container.pickup .location-scores .locations-scores tbody  tr td:nth-child(1)",
        textRegistroShipment: ".scores-container.shipment .row.table-meta .col-md-6:nth-child(1)",
        textRegistroPickup: ".scores-container.pickup .row.table-meta .col-md-6:nth-child(1)",
        page2Shipment: ".scores-container.shipment .row.table-meta .table-pagination a[data-page='2']",
        page1Shipment: ".scores-container.shipment .row.table-meta .table-pagination a[data-page='1']",
        page2Pickup: ".scores-container.pickup .row.table-meta .table-pagination a[data-page='2']",
        page1Pickup: ".scores-container.pickup .row.table-meta .table-pagination a[data-page='1']",
        comboboxItensPerPageShipment: ".scores-container.shipment [role='combobox']",
        comboboxItensPerPagePickup: ".scores-container.pickup [role='combobox']",
        option25ItensShipment: ".scores-container.shipment [role='combobox'] .rw-popup ul li:nth-child(2)",
        option25ItensPickup: ".scores-container.pickup [role='combobox'] .rw-popup ul li:nth-child(2)",
        shipmentIndicatorsNamesHeadTable: ".shipment .indicators thead th",
        pickupIndicatorsNamesHeadTable: ".pickup .indicators thead th",
        shipmentIndicatorsWeight: ".shipment input", //Multiple
        pickupIndicatorsWeight: ".pickup input", //Multiple
        saveShipmentIndicatorManagementButton: ".shipment .btn-primary",
        savePickupIndicatorManagementButton: ".pickup .btn-primary"
    },
    locations: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='id']",
        cnpj: "[name='documents.cnpj']",
        description: "[name='description']",
        tradingName: "[name='tradingName']",
        zip: "[name='address.zip']",
        number: "[name='address.number']",
        address1: "[name='address.address1']",
        address2: "[name='address.address2']",
        neighbourhood: "[name='address.neighbourhood']",
        city: "[name='address.city']",
        state: "[name='address.state']",
        country: "[name='address.country']",
        telCountryCode: "[name='address.telephone.countryCode']",
        telNumber: "[name='address.telephone.number']",
        handlingTime: ".row:nth-child(9) [name='handlingTime']",
        handlingTax: "[name='handlingTax']",
        loading: ".loading",
        list: ".locations-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        checkSendByStore: "[name*='canShipToCustomer']",     //S
        checkPickup: "[name*='canPickupInStore']",           //P
        checkSendToStore: "[name*='canShipToStore']",        //ST
        checkReceiveStore: "[name*='canReceiveFromStore']",  //PP
        checkReserve: "[name*='canReserveInStore']",         //R
        selectedBasicInformation: "#react-tabs-38[aria-selected='true']",
        centerCostField: "input[name*='costCenter']",
        checkAccountField: "input[name*='checkAccount']",
        businessCodeField: "input[name*='businessCode']",
        brandField: ".rw-input.rw-dropdown-list-input",
        tabFinanceiro: ".react-tabs__tab-list li:nth-child(2)",
        registerNewCostOrderType: ".row.costs .btn-primary",

        //Modal Custo por tipo de pedido
        valueCostField: ".content #value",
        startDateCost: ".content input[placeholder='Data de início']",
        endDateCost: ".content input[placeholder='Data de fim']",
        radioAtSight: "input[name='transferType'][value='atSight']",
        radioInInstallment: "input[name='transferType'][value='inInstallments']",
        shipmentDeliveryModality: ".content input[name='modules.deliveryType'][value='SHIPMENT']",
        pickupDeliveryModality: ".content input[name='modules.deliveryType'][value='PICKUP']",
        radioCreditCardPaymentMethod: ".content input[name='modules.paymentMethod'][value='CREDIT_CARD']",
        radioDebitCardPaymentMethod: ".content input[name='modules.paymentMethod'][value='DEBIT_CARD']",
        radioBoletoPaymentMethod: ".content input[name='modules.paymentMethod'][value='BOLETO']",
        radioCashPaymentMethod: ".content input[name='modules.paymentMethod'][value='CASH']",
        minInstallments: ".content #minInstallments",
        maxInstallments: ".content #maxInstallments",
        saveButton: ".cost .btn-primary",
        reprocessDataButton: ".financial .complementary-header button.btn-primary",
        removeTaxFreightButton: ".tax .btn-remove",
        deleteAdditionalCost: ".additional-costs tr .actions button", // + text
        deleteIncentiveCost: ".incentives tr button", // + text
        additionalCostButton: ".additional-costs .btn-primary",
        additionalCostField: ".additional-cost-form #value",
        startDateAdditionalCost: ".additional-cost-form [placeholder='Data de início']",
        endDateAdditionalCost: ".additional-cost-form [placeholder='Data de fim']",
        descAdditionalCost: ".additional-cost-form #name",
        saveAdditionalCostButton: ".additional-cost-form button[type='submit']",
        incentiveCostButton: ".incentives .btn-primary",
        incentiveCostField: ".incentive-form #value",
        startDateIncentiveCost: ".incentive-form [placeholder='Data de início']",
        endDateIncentiveCost: ".incentive-form [placeholder='Data de fim']",
        shipmentIncentiveCostDeliveryModality: "input[name='deliveryType'][value='SHIPMENT']",
        pickupIncentiveCostDeliveryModality: "input[name='deliveryType'][value='PICKUP']",
        saveIncentiveCostButton: ".incentive-form button[type='submit']",
        taxValueField: ".freight-taxes #value",
        startDateTax: ".freight-taxes [placeholder='Data de início']",
        endDateTax: ".freight-taxes [placeholder='Data de fim']",
        saveButtonTax: ".freight-taxes button[type='submit']",
        editFreightDestinationButton: ".freight-destination .btn-default",
        headerFreightsDestination: ".freight-destination-form h3",
        catchOrderFreightDestinationButton: ".freight-destination-form .btn-outline-secondary.left",
        selectedCatchOrderFreightDestinationButton: ".freight-destination-form .btn-outline-secondary.left.selected",
        productOriginFreightDestinationButton: ".freight-destination-form .btn-outline-secondary.middle",
        selectedProductOriginFreightDestinationButton: ".freight-destination-form .btn-outline-secondary.middle.selected",
        companyAccountFreightDestinationButton: ".freight-destination-form .btn-outline-secondary.right",
        selectedCompanyAccountFreightDestinationButton: ".freight-destination-form .btn-outline-secondary.right.selected",
        freightsDestinationCancelButton: ".freight-destination-form .footer button",
        freightsDestinationSaveButton: ".freight-destination-form .footer a"
    },
    macroregions: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='id']",
        tradingName: "[name='name']",
        startZip: "[name='start']",
        endZip: "[name='end']",
        btnAddZip: ".form-group.boxed .btn.btn-primary",
        loading: ".loading",
        list: ".macroregions-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        elementStatus: "[for='togglestatus']",
        elementCheckboxEnvio: "[name='SHIPMENT']",
        elementCheckboxRetirada: "[name='PICKUP']",
        labelDetalhesPedido: '#app-title h1',
        fieldName: "[name='name']",
        tooltipAtivarFluxos: "[for='deliveryType'] .tooltip-icon",
        buttonremoveCEP: ".fa.fa-remove",
        //Elementos desabilitados
        elementIDDesabilitado: "[name='id'][readonly]",
        elementNameDesabilitado: "[name='name'][readonly]",
        elementStatusDesabilitado: "[type='checkbox'].read-only",
        elementCheckboxEnvioDesabilitado: "[name='SHIPMENT'][disabled]",
        elementCheckboxRetiradaDesabilitado: "[name='PICKUP'][disabled]",
        elementFaixaCEPInicialDesabilitado: ".range-list .form-control[disabled]",
        elementFaixaCEPFinalDesabilitado: ".range-list .form-control[disabled]",
        //Elementos obrigatórios
        fieldIDRequired: "//input[@id='id']/../..//div[contains(@class, 'has-error')]",
        fieldNameRequired: "//input[@id='name']/../..//div[contains(@class, 'has-error')]",
        fieldCEPStartRequired: "//input[@id='start']/../..//div[contains(@class, 'has-error')]",
        fieldCEPFinalRequired: "//input[@id='end']/../..//div[contains(@class, 'has-error')]",
        fieldCheckboxShipment: "//input[@name='SHIPMENT']/../../../../..//div[contains(@class, 'has-error')]",
        fieldCheckboxPickup: "//input[@name='PICKUP']/../../../../..//div[contains(@class, 'has-error')]",
        //Elementos em Modalidade Frete
        elementButtonAddPriority: "//i[@class='fa fa-plus']/..",
        modalAddMacroregion: ".add-macroregion",
        modalEditMacroregion: ".edit-priorization",
        elementButtonModalAddMacroregion: ".add-macroregion .btn.btn-primary",
        firstElementInputModalAddMacroregion: ".macroregion-checkbox-list.checkbox-list input",
        firstElementLabelModalAddMacroregion: ".macroregion-checkbox-list.checkbox-list label",
        macroAdded: ".macroregions-list .index .macroregion",
        firstMacroregionAdded: ".priority-1 div",
        secondMacroregionAdded: ".priority-2 div",
        thirdMacroregionAdded: ".priority-3 div",
        elementButtonRemoveMacroregion: "//i[@class= 'fa fa-remove']/..",
        elementButtonEditMacroregion: "//i[@class='fa fa-pencil']/..",
        item1NotSelected: ".droppable.not-selected .draggable",
        areaDroppableNotSelected: ".droppable.not-selected",
        areaDroppableSelected: ".droppable.selected",
        item1Selected: ".droppable.selected .draggable",
        elementButtonModalAdd: ".edit-priorization button.btn.btn-primary",
        itemsSelected: ".droppable.selected .draggable",
    },
    pickup: {
        saveButton: ".fa.fa-check",
        description: '[name*="name"].form-control',
        treatmentDeadLine: '[name*="billingDeadline"].form-control',
        pickupDeadLine: '[name*="pickupDeadline"].form-control',
        reserveDeadLine: '[name*="reserveDeadline"].form-control',
        deadLine: '.rw-widget-input.rw-input',
        cutHour: "[name='deadlineTime']",
        identification: '#content [name*="id"]',
        identificationReadOnly: '[name*="id"][readonly]',
        statusButton: '[for*="toggleactive"].toggle-block',
    },
    pools: {
        btn: ".complementary-header .btn.btn-primary",
        tradingName: "[name='name']",
        loading: ".loading",
        list: ".pools table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary"
    },
    shipment_carriers: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='id']",
        zipCode: "[name='zipCode']",
        weight: "[name='weight']",
        btnSearch: ".btn.btn-primary.btn-search",
        description: "[name='companyName']",
        zip: "[name='address.zip']",
        number: "[name='address.number']",
        address1: "[name='address.address1']",
        address2: "[name='address.address2']",
        neighbourhood: "[name='address.neighbourhood']",
        city: "[name='address.city']",
        state: "[name='address.state']",
        country: "[name='address.country']",
        cnpj: "[name='documents.cnpj']",
        tradingName: "[name='tradingName']",
        stateInsc: "[name='documents.stateInscription']",
        loading: ".loading",
        list: ".carriers-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        toggleTrackCode: '.toggle [for*=toggleshowTrackingNumber]',
        trackingPrefix: "[name*='tracking.prefix']",
        trackingSufix: "[name*='tracking.sufix']",
        trackingNumberSize: "[name*='tracking.numberSize']",
        trackingStartNumber: "[name*='tracking.startNumber']",
        trackingEndNumber: "[name*='tracking.endNumber']",
        trackingCurrentNumber: "[name*='tracking.currentNumber']",
        toggleReverseAddress: '.toggle [for*=toggleshowReverseAddressForm]',
        reverseZipCode: "[name*='reverseAddress.zip']",
        reverseAddrress1: "[name*='reverseAddress.address1']",
        reverseNumber: "[name*='reverseAddress.number']",
        reverseAddress2: "[name*='reverseAddress.address2']",
        reverseNeighbourhood: "[name*='reverseAddress.neighbourhood']",
        reverseCity: "[name*='reverseAddress.city']",
        reverseState: "[name*='reverseAddress.state']",
        reverseCountry: "[name*='reverseAddress.country']",
    },
    shipment_freight_methods: {
        btn: ".complementary-header .btn.btn-primary",
        id: "[name='id']",
        description: "[name='name']",
        loading: ".loading",
        list: ".methods-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        labelDetalhesPedido: "#app-title h1",
        locationPoolTab: "#react-tabs-2",
        toggleOnButton: ".toggle-block .on",
        toggleOffButton: ".toggle-block .off",
        toggleButton: ".toggle-block[for*='toggleundefined']",
        //Elementos desabilitados
        elementFieldIDReadOnly: "[name='id'][readonly]",
        elementFieldNameReadOnly: "[name='name'][readonly]",
        elementFieldBillingDeadlineReadOnly: "[name='billingDeadline'][readonly]",
        elementCheckboxStatusReadOnly: "#toggleactive.read-only",
        elementFieldDeadlineTimeReadOnly: "[name='deadlineTime'][readonly]",
        elementFieldAfterDeadlineReadOnly: "[for='toggleallowAfterDeadline'].disabled",
        elementFieldPriority1ReadOnly: ".rw-dropdown-list.rw-widget.rw-state-readonly",
    },
    shipment_freight_tables: {
        btn: ".complementary-header .btn.btn-primary",
        shipping_dropdown: ".rw-i.rw-i-caret-down",
        shipping_carrier_option: "#rw_1_input ul .rw-list-option",
        shipping_method_option: "#rw_2_input ul .rw-list-option",
        contract_id: "[name='id']",
        loading: ".loading",
        list: ".carrier-contract-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        elementDropDownLocation: ".location-selector",
        elementButtonAddZip: ".form-group.boxed button",
        labelDetalhesPedido: "#app-title h1",
        elementDropDownTransportadoraDesabilitado: "//input[@name='carrier']/../../../..//div[@aria-readonly='true']",
        elementDropDownModalidadeDesabilitado: "//input[@name='freightMethod']/../../../..//div[@aria-readonly='true']",
        elementIdContratoDesabilitado: "[name='id'][readonly]",
        elementFiliaisDesabilitado: "[name='locationIds'].rw-state-readonly",
        elementHorarioCorteDesabilitado: "[name='deadlineTime'][aria-readonly='true']",
        elementStatusDesabilitado: "#toggleundefined.read-only",
        //Tabelas de frete (Tela de Listagem).
        locationFilter: "#content .btn.btn-link.dropdownlist-toggle span",
        searchField: ".search-field .form-group input",
        locationsDeleteButton: "[name='locationIds'] li button",
        locationsDropDownButton: "[name='locationIds'] [role='presentational']",
    },
    stock_disabled: {
        loading: ".loading",
        list: ".stockouts table",
        popupReactiveProduct: ".ReactModal__Content.ReactModal__Content--after-open.reactivate-content",
        optionComboboxMotivo: "//label[contains(text(), 'Motivo')]/..//li[1]",
        dropDownMotivo: ".rw-dropdown-list-input .rw-placeholder",
        saveButton: ".actions .btn.btn-primary",
        columnLocationNameTable: "tbody tr td:nth-child(3)"
    },
    stock_physical: {
        dropDownLocation: '.location-selector .dropdownlist-toggle',
        searchNameLocation: ".location-selector .search-field .form-control",
        labelSearchSKU: 'form.search-form .form-control',
        summitSearchButton: "form.search-form button.form-control-feedback",
        blockButton: ".table td.actions button.btn-xs",
        blockInLotButton: ".block-stocks button",
        locationNameLineTable: "tbody tr td:nth-child(3)",
        buttonDropChannel: ".rw-widget-picker button",
        secondElementDropChannel: ".rw-list li:nth-child(2)",
        emptyTable: ".empty-table"
    },
    stock_protection: {
        removeButton: ".remove.pull-right",
        uploadArea: ".upload-area [type*='file']",
        skuUploadButton: ".import-by .btn.btn-default",
        toastUpload: ".upload-badge-icon",
        headerCloseButton: ".upload-status-header .fa.fa-close",
        headerFileName: ".file-info .file-name",
        headerClearButton: ".clear",
        textStatusUpload: ".file-message .message",
    },
    stock_virtual: {
        btn: ".complementary-header .btn.btn-primary",
        location_dropdown_button: "//label[contains(text(), 'Filial')]/../div/div[1]/div",//"#rw_1_input button",
        location_options: "//label[contains(text(), 'Filial')]/../div/div[2]//li[1]",//"#rw_1_input ul .rw-list-option",
        sku: "[name='skuId']",
        type_dropdown_button: "//label[contains(text(), 'Tipo')]/../div/div/div",//"#rw_2_input button",
        type_options: "#rw_2_input ul .rw-list-option",
        qty: "[name='quantity']",
        pre_sales_start_pre_sale: "[name='salesStartsAt']",
        pre_sales_end_pre_sale: "[name='salesEndsAt']",
        pre_sales_start_billing: "[name='billingStartsAt']",
        virtual_available: "[name='deliveryDate']",
        receiving_estimate: "[name='daysToDelivery']",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
    },
    users_chaordic: {
        loading: ".loading",
        list: ".chaordic.users-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary"
    },
    users_cockpit: {
        btn: ".complementary-header .btn.btn-primary",
        name: "[name='name']",
        permission: "[name='permission']",
        permission_admin: "[name='permission'][value='admin']",
        permission_courier_manager: "[name='permission'][value='courrierManager']",
        permission_location_manager: "[name='permission'][value='locationManager']",
        permission_analyze_manager: "[name='permission'][value='analyzeManager']",
        permission_sac: "[name='permission'][value='sac']",
        permission_read_only: "[name='permission'][value='readOnly']",
        permission_teste_de_validacao: "[name='permission'][value='testeDeValidacao']",
        email: "[name='email']",
        loading: ".loading",
        list: ".users-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        messageDisable: ".alert-danger"
    },
    users_in_store: {
        btn: ".complementary-header .btn.btn-primary",
        name: "[name='name']",
        permission: "[name='permission']",
        permission_store_operator: "[name='permission'][value='operator']",
        permission_admin_store: "[name='permission'][value='inStoreAdmin']",
        permission_location_manager: "[name='permission'][value='locationManager']",
        enrollment: "[name='enrollment']",
        password: "[name='password']",
        generate_password_btn: ".btn.btn-default.btn-block.list-locations",
        location_dropdown_button: ".rw-select button",
        location_options: "#rw_3_listbox .rw-list-option",
        loading: ".loading",
        list: ".users-list table",
        modal: ".bootbox.modal",
        modal_body: ".bootbox-body",
        modal_ok_btn: ".modal-footer .btn.btn-primary",
        elementUser: "#user_enrollment",
        elementPass: "#user_password",
        elementBtn: "input[type='submit']",
        messageDisable: ".alert-danger",
        buttonNaoModalExcluir: ".modal-footer [data-bb-handler='cancel']",
        buttonSimModalExcluir: ".modal-footer [data-bb-handler='confirm']",
        comboboxFilter: "[role='presentational']",
        searchField: "input.form-control",
        columnEnrollmentTable: "tbody tr td:nth-child(2)",
        columnNameTable: "tbody tr td:nth-child(1)",
        searchButton: "button.form-control-feedback"
    },
    users_permissions: {
        btnProxima: ".complementary-header .btn.btn-primary",
        inputName: "input[name='name']",
        elementRadioFiliaisGrupoEmpresarialEspecifico: "input[value='company']",
        elementRadioFiliaisMarcaEspecifica: "input[value='brand']",
        elementRadioFiliaisEspecificas: "input[value='location']",
        elementRadioFiliaisRegionalEspecifica: "input[value='locationGroup']",
        elementRadioTodasFiliaisSistema: "input[value='all']",
        elementButtonAnterior: "button.btn-previous",
        elementButtonSalvarPermissao: ".btn.btn-primary .fa-check",
        elementToast: ".toast.toast-success",
        elementComboClient: "#header-menu",
        elementModalDelete: ".modal-content",
        elementButtonSimModalDelete: "button[data-bb-handler='confirm']",
        linksMenu: ".nav a",
        elementRadioFiliaisMarcaEspecific: "input[value='brand']",

        inputNameDisabled: "[name='name'][readonly]",
        radioFiliaisGrupoEmpresarialEspecificoDisabled:".form-group input[value='company'][disabled]",
        radioFiliaisMarcaEspecificaDisabled: ".form-group input[value='brand'][disabled]",
        radioFiliaisRegionalEspecificaDisabled: ".form-group input[value='locationGroup'][disabled]",
        radioFiliaisEspecificasDisabled: ".form-group input[value='location'][disabled]",
        radioTodasFiliaisSistemaDisabled: ".form-group input[value='all'][disabled]",
        buttonProxima: ".btn-next",
    },
    wallet:{
        voucherName: "#name",
        voucherCode: "#code",
        voucherEmail: "#email",
        voucherOrder: "#orderId",
        voucherDoc: "#vatNumber",
        voucherDropSituation: "[role='combobox']",
        voucherCreateNewButton: ".complementary-header .btn-primary",
        voucherDateDropDown: ".react-tabs__tab-panel--selected .date-range .fa-angle-down",
        voucherSearchButton: ".search-form .btn-primary",
        voucherStatus: ".search-form [role='presentational']",
        voucherUnifierButton: ".actions.pull-left .btn-primary",
        unifierVoucherConfirm: ".footer .btn-primary",
        unifierVoucherLocation: ".location button",
        unifierVoucherNewCode: ".generated-code .value",
        unifierVoucherAmount: ".confirmation-content .amount .value",
        unifierVoucherOk: "#unificationCompleted",
        newVoucherReason: "#reason",
        newVoucherName: "#name",
        newVoucherValue: "#balance",
        newVoucherDoc: "#vatNumber",
        newVoucherEmail: "#email",
        newVoucherOrderId: "#orderId",
        newVoucherLocation: "//label[@for='locationId']/../div//button",
        newVoucherChannel: "//label[@for='channelId']/../div//button",
        newVoucherSaveButton: ".btn-primary",
        newVoucherBackButton: ".back-button",
        newVoucherCode: ".account-code strong",
        newVoucherModalOk: ".clearfix .btn-primary",
        reportTabs: ".react-tabs__tab-list span", // + text
        reportSelectedTabTitle: ".react-tabs__tab-panel--selected h2", // + text
        reportDocSearchField: ".react-tabs__tab-panel--selected .vatnumber-search input",
        reportDocSearchButton: ".react-tabs__tab-panel--selected .vatnumber-search button",
        reportSeeButton: ".deliveries .actions a.btn-default", // Multiple elements
        reportSearchStatusCombo: ".react-tabs__tab-panel--selected [role='combobox'] button",
        detailVoucherTitle: ".account-info h2",
    }
}